/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-11-09 12:07:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import product.model.vo.*;
import board.model.vo.PageInfo;
import java.text.SimpleDateFormat;
import java.io.File;
import member.model.vo.Member;

public final class product_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/common/ad.jsp", Long.valueOf(1604923087294L));
    _jspx_dependants.put("/resources/globalVariable.jsp", Long.valueOf(1604828540617L));
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1604923087459L));
    _jspx_dependants.put("/WEB-INF/views/common/nav.jsp", Long.valueOf(1604923087467L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1604923087451L));
    _jspx_dependants.put("/WEB-INF/views/common/tom.jsp", Long.valueOf(1604923087496L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("product.model.vo");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("board.model.vo.PageInfo");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   ArrayList<String> locationList = (ArrayList<String>) request.getAttribute("locationList");
   ArrayList<String> locationList2 = (ArrayList<String>) request.getAttribute("locationList2");
   ArrayList<String> locationList3 = (ArrayList<String>) request.getAttribute("locationList3");
   String location1 = (String) request.getAttribute("location1");
   String location2 = (String) request.getAttribute("location2");
   String location3 = (String) request.getAttribute("location3");

   String option = (String)request.getAttribute("option");
   ArrayList<Product> pList = (ArrayList<Product>)request.getAttribute("pList");
   ArrayList<Product_File> pfList = (ArrayList<Product_File>)request.getAttribute("pfList");
   PageInfo pi = (PageInfo)request.getAttribute("pi");
   
   int listCount = pi.getListCount();
   int currentPage = pi.getCurrentPage();
   int maxPage = pi.getMaxPage();
   int startPage = pi.getStartPage();
   int endPage = pi.getEndPage();
   
   String option2 = (String) request.getAttribute("option2");
   String word = (String) request.getAttribute("word");
   

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>로컬마켓</title>\r\n");
      out.write('\r');
      out.write('\n');

	String context = request.getContextPath();

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar context = \"");
      out.print( context );
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.print( context );
      out.write("/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<link rel = \"icon\" href = \"");
      out.print( context );
      out.write("/favicon.ico\">");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/base.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/content-area.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/content.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/product_list.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"wrap\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member)session.getAttribute("loginMember");
	String pImageName = null;
	if(loginMember != null && loginMember.getpImage() != null) {
		File f = new File(loginMember.getpImage());
		pImageName = f.getName();
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id='header'>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print( context );
      out.write("/\"> \r\n");
      out.write("\t\t\t\t<img id='logo-img' alt=\"로컬마켓\" src=\"");
      out.print( context );
      out.write("/resources/images/rocket.png\"></a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print( context );
      out.write("/\"><span id=\"logo-text\">로켓</span></a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t <form action=\"allSearch.all\" method=\"get\" class=\"AllSearchForm\">\r\n");
      out.write("       \t \t<div id=\"header-search\">\r\n");
      out.write("            <input type=\"text\" name=\"word\" placeholder=\"검색어를 입력하세요!\"> \r\n");
      out.write("            <button class=\"glyphicon glyphicon-search\" id=\"AllSearchBtn\"></button>\r\n");
      out.write("         \t</div>\r\n");
      out.write("         </form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t");
 if(loginMember == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"account\">\r\n");
      out.write("\t\t\t\t\t<form action=\"");
      out.print( context );
      out.write("/login.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"id-area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"idInput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" id=\"login\" value=\"로그인\">로그인</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"pw-area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"pwInput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" id=\"signup\" value=\"회원가입\" onclick=\"location.href='");
      out.print( context );
      out.write("/joinForm.do'\">회원가입</button><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" id=\"find\" value=\"ID/PW찾기\" onclick=\"findIDPW();\" style=\"float: right; width: 80px; font-weight:bold; border:none;\">\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"account_info\">\r\n");
      out.write("\t\t\t\t<div id=\"profileArea\">\r\n");
      out.write("\t\t\t\t");
 if(loginMember.getpImage() == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<label id=\"memberIcon\" class=\"glyphicon glyphicon-user\" style=\"top:15px; right: 30px;\"></label>\r\n");
      out.write("\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<img id=\"memberImg\" src=\"");
      out.print( context );
      out.write("/userProfile_uploadFiles/");
      out.print( pImageName );
      out.write("\">\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"membername\">");
      out.print( loginMember.getNickName() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"memberbtn\">\r\n");
      out.write("                  <button id='logoutBtn' onclick=\"location.href='");
      out.print( context );
      out.write("/logout.do'\">로그아웃</button>\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <button id=\"myPageBtn\" onclick=\"location.href='");
      out.print( context );
      out.write("/myPage.do'\">마이페이지</button>\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <button id=\"messageBtn\" onclick=\"location.href='");
      out.print( context );
      out.write("/message.do'\">쪽지함</button>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div id=\"alarm\">\r\n");
      out.write("                  <button class=\"glyphicon glyphicon-bell\" onclick=\"location.href='");
      out.print( context );
      out.write("/receiveP.do'\"></button>\r\n");
      out.write("               </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t");
 if(loginMember != null) { 
      out.write("\r\n");
      out.write("\t\t\tvar openProfile = function(closeCallback) {\r\n");
      out.write("\t\t\t    var win = window.open('setProfileImgForm.do', 'setProfileImgForm', 'width=500, height=450');\r\n");
      out.write("\t\t\t    var interval = window.setInterval(function() {\r\n");
      out.write("\t\t\t        try {\r\n");
      out.write("\t\t\t            if (win == null || win.closed) {\r\n");
      out.write("\t\t\t                window.clearInterval(interval);\r\n");
      out.write("\t\t\t                closeCallback(win);\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        catch (e) {\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    }, 1000);\r\n");
      out.write("\t\t\t    return win;\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"profileArea\").onclick = function() {\r\n");
      out.write("\t\t\t\topenProfile(function(win) {\r\n");
      out.write("\t\t\t\t\tlocation.reload(true);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t");
 } else { 
      out.write("\r\n");
      out.write("      \tfunction findIDPW() {\r\n");
      out.write("      \t\twindow.open('findIDPWForm.do', 'findIDPWForm', 'width=500, height=135');\r\n");
      out.write("\t\t}\r\n");
      out.write("      \r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("      <div id=\"content-area\">\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>nav</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/nav.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"nav\">\r\n");
      out.write("   \r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("            \r\n");
      out.write("            <!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("            <div id=\"menu-area\">\r\n");
      out.write("               <ul class=\"out-menu\">\r\n");
      out.write("                  <label class=\"glyphicon glyphicon-camera\"><div>중고물품</div></label>\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/list.pro'\">중고 물품보기</button></li>\r\n");
      out.write("                  ");
 if(loginMember != null) { 
      out.write("\r\n");
      out.write("                     <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/registerForm.pro'\">중고 물품등록</button></li>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("               <ul class=\"out-menu\">\r\n");
      out.write("                  <label class=\"glyphicon glyphicon-tag\"><div>공동구매</div></label>\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/groupList.do'\">공동구매 목록조회</button></li>\r\n");
      out.write("                  ");
 if(loginMember != null && loginMember.getRankCode() == 99) { 
      out.write("\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/groupWriteForm.do'\">공동구매 물품등록</button></li> \r\n");
      out.write("\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("               <ul class=\"out-menu menuBtn\" onclick=\"location.href='");
      out.print( context );
      out.write("/boardList.do'\">\r\n");
      out.write("                  <label class=\"glyphicon glyphicon-list\" class=\"menuBtn\"><div class=\"menuBtn\">자유게시판</div></label>\r\n");
      out.write("               </ul>\r\n");
      out.write("               ");
 if(loginMember != null && loginMember.getRankCode() == 99) { 
      out.write("\r\n");
      out.write("               <ul class=\"out-menu\">\r\n");
      out.write("                  <label class=\"glyphicon glyphicon-lock\"><div>관리자</div></label>\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/managerInfo.do'\">회원 정보 관리</li>\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/managerreport.do'\">신고 목록 관리</li>\r\n");
      out.write("               </ul>\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Top of this Month</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/tom.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"tom\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<b>이달의 로켓왕!</b>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table id=\"tom-table\">\r\n");
      out.write("\t\t\t<tr id=\"table-head\">\r\n");
      out.write("\t\t\t\t<th>No.</th>\r\n");
      out.write("\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t<th>거래 수</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<div id=\"loading\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print( context );
      out.write("/resources/images/loading.gif\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: 'topOfMonth.do',\r\n");
      out.write("\t\ttype: 'post',\r\n");
      out.write("\t\tdata: {first: 1, last: 3},\r\n");
      out.write("\t\tsuccess: function(data) {\t\r\n");
      out.write("\t\t\tvar table = document.getElementById(\"tom-table\");\r\n");
      out.write("\t\t\tfor(var i in data) {\r\n");
      out.write("\t\t\t\tvar tr = document.createElement(\"tr\");\r\n");
      out.write("\t\t\t\tvar td1 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\ttd1.innerHTML = data[i].rank;\r\n");
      out.write("\t\t\t\tvar td2 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\ttd2.innerHTML = data[i].nickname;\r\n");
      out.write("\t\t\t\tvar td3 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\ttd3.innerHTML = data[i].count;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttr.appendChild(td1);\r\n");
      out.write("\t\t\t\ttr.appendChild(td2);\r\n");
      out.write("\t\t\t\ttr.appendChild(td3);\r\n");
      out.write("\t\t\t\ttable.appendChild(tr);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('#tom-table').show();\r\n");
      out.write("\t\t\t$('#loading').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            <!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <script>\r\n");
      out.write("            $('.out-menu').click(function(){\r\n");
      out.write("               $(this).children().next().slideToggle();\r\n");
      out.write("            });\r\n");
      out.write("         </script>\r\n");
      out.write("         \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <div id=\"content\">\r\n");
      out.write("            <h1>중고 물품</h1>\r\n");
      out.write("\r\n");
      out.write("            <br> <br>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"categorySearch.pro\" method=\"get\" class=\"catesearch\" id=\"catesearch\" onsubmit=\"submitForm();\">\r\n");
      out.write("             <select name=\"location1\" id=\"location1\" onchange=\"sidoChange();\">\r\n");
      out.write("                     <option value=\"0\">시/도</option>\r\n");
      out.write("                     ");
 for(String location : locationList) { 
      out.write("\r\n");
      out.write("                     <option>");
      out.print( location );
      out.write("</option>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                     </select>\r\n");
      out.write("                     <select name=\"location2\" id=\"location2\" onchange=\"sigunguChange();\" disabled>\r\n");
      out.write("                     \t<option value=\"0\">시/군/구</option>\r\n");
      out.write("                     \t");
 if(locationList2 != null) { 
      out.write("\r\n");
      out.write("                     \t");
 for(String location : locationList2) { 
      out.write("\r\n");
      out.write("\t                    <option>");
      out.print( location );
      out.write("</option>\r\n");
      out.write("\t                    ");
 } 
      out.write("\r\n");
      out.write("\t                    ");
 } 
      out.write("\r\n");
      out.write("                     </select>\r\n");
      out.write("                     <select name=\"location3\" id=\"location3\" onchange=\"dongChange();\" disabled>\r\n");
      out.write("                     \t<option value=\"0\">동</option>\r\n");
      out.write("                     \t");
 if(locationList3 != null) { 
      out.write("\r\n");
      out.write("                     \t");
 for(String location : locationList3) { 
      out.write("\r\n");
      out.write("\t                     <option>");
      out.print( location );
      out.write("</option>\r\n");
      out.write("\t                    ");
 } 
      out.write("\r\n");
      out.write("\t                    ");
 } 
      out.write("\r\n");
      out.write("             </select>\r\n");
      out.write("               <br> \r\n");
      out.write("               <select name=\"categorySearch\" id=\"categorySearch\">\r\n");
      out.write("                  <option value=\"0\">카테고리 선택</option>\r\n");
      out.write("                  <option value=\"의류\">의류</option>\r\n");
      out.write("                  <option value=\"패션잡화\">패션잡화</option>\r\n");
      out.write("                  <option value=\"디지털가전\">디지털가전</option>\r\n");
      out.write("                  <option value=\"뷰티/미용\">뷰티/미용</option>\r\n");
      out.write("                  <option value=\"유아/출산\">유아/출산</option>\r\n");
      out.write("                  <option value=\"기타\">기타</option>\r\n");
      out.write("               </select>\r\n");
      out.write("\r\n");
      out.write("               <script> \r\n");
      out.write("                   var categorySearch = document.getElementById(\"categorySearch\");\r\n");
      out.write("                   for(var i = 0; i < categorySearch.children.length; i++) {\r\n");
      out.write("                      if(categorySearch.children[i].value === '");
      out.print( option );
      out.write("') { \r\n");
      out.write("                         categorySearch.children[i].setAttribute('selected', '');\r\n");
      out.write("                      }\r\n");
      out.write("                   }\r\n");
      out.write("                   \r\n");
      out.write("                   /* function cateCheck() {\r\n");
      out.write("                     if(document.getElementById('categorySearch').value == '0') {\r\n");
      out.write("                        alert('카테고리를 선택해주세요');\r\n");
      out.write("                        return false;\r\n");
      out.write("                     } else {\r\n");
      out.write("                        return true;   \r\n");
      out.write("                     } \r\n");
      out.write("                  } */\r\n");
      out.write("                </script>\r\n");
      out.write("\r\n");
      out.write("               <button id=\"search\" type=\"submit\">검색</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("            <div id=\"item-list-product\">\r\n");
      out.write("               ");
 if(pList.isEmpty() || pfList.isEmpty()) { 
      out.write("\r\n");
      out.write("               <div class=\"none\">\r\n");
      out.write("                  <label class=\"glyphicon glyphicon-alert\"> </label> <label>조회된\r\n");
      out.write("                     중고 물품이 없습니다.</label> <br> <br> <br> <label id=\"golist\"\r\n");
      out.write("                     class=\"glyphicon glyphicon-hand-right\"></label>\r\n");
      out.write("                  <button id=\"golist\"\r\n");
      out.write("                     onclick=\"location.href='");
      out.print( context );
      out.write("/list.pro'\" style=\"width:300px; background-color: #FFFCF5;\">상품\r\n");
      out.write("                     목록으로 가기!</button>\r\n");
      out.write("                  <br> <br> <label id=\"goRegister\"\r\n");
      out.write("                     class=\"glyphicon glyphicon-hand-right\"></label>\r\n");
      out.write("                  <button id=\"goRegister\"\r\n");
      out.write("                     onclick=\"location.href='");
      out.print( context );
      out.write("/registerForm.pro'\" style=\"width:300px; background-color: #FFFCF5;\">상품\r\n");
      out.write("                     등록하러 가기!</button>\r\n");
      out.write("               </div>\r\n");
      out.write("               ");
 } else { 
      out.write("\r\n");
      out.write("               ");
 for(int i = 0; i < pList.size(); i++) { 
      out.write("\r\n");
      out.write("               ");
 Product p = pList.get(i); 
      out.write("\r\n");
      out.write("                  <div class=\"item\" align=\"center\">\r\n");
      out.write("                     <input type=\"hidden\" value=\"");
      out.print( p.getProductId() );
      out.write("\" name=\"productNum\">\r\n");
      out.write("                     ");
 for(int j = 0; j < pfList.size(); j++){ 
      out.write("\r\n");
      out.write("                        ");
 Product_File pf = pfList.get(j); 
      out.write("\r\n");
      out.write("                     ");
 if(pf.getP_num() == p.getProductId()){ 
      out.write("\r\n");
      out.write("                        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/product_uploadFiles/");
      out.print( pf.getChangeName() );
      out.write("\">\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                     <br>\r\n");
      out.write("                     <div class=\"itemLocation\">");
      out.print( p.getLocation1() );
      out.write(' ');
      out.print( p.getLocation1().equals(p.getLocation2()) ? "" : p.getLocation2() );
      out.write(' ');
      out.print( p.getLocation3() );
      out.write("</div>\r\n");
      out.write("                     <p>\r\n");
      out.write("                        ");
 if (p.getRankCode() == 4) { 
      out.write(" \r\n");
      out.write("                           <label id=\"star\" class=\"glyphicon glyphicon-star\"></label>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        &nbsp;&nbsp;No.\r\n");
      out.write("                        ");
      out.print( p.getProductId() );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;");
      out.print( p.getTitle() );
      out.write("<br>\r\n");
      out.write("                        ");
      out.print( p.getPrice() );
      out.write("원&nbsp;&nbsp;&nbsp;&nbsp;조회수 :\r\n");
      out.write("                        ");
      out.print( p.getProductCount() );
      out.write("\r\n");
      out.write("                     </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("                  <select id=\"so\" name=\"searchOption\">\r\n");
      out.write("                     <option value=\"TITLE\">제목</option>\r\n");
      out.write("                     <option value=\"MEMBERNAME\">닉네임</option>\r\n");
      out.write("                  </select> \r\n");
      out.write("                  <input type=\"text\" id=\"word\" name=\"word\" size=\"20\" placeholder=\"검색어를 입력해주세요\" value=\"");
      out.print( word == null ? "" : word );
      out.write("\">\r\n");
      out.write("                  <button id=\"searchWord\" type=\"button\">검색</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <script>\r\n");
      out.write("                  var context = document.location.href.split(\"?\");\r\n");
      out.write("                  if(typeof context[1] == \"undefined\") {\r\n");
      out.write("                     context[1] = \"\";\r\n");
      out.write("                  } else {\r\n");
      out.write("                     context[1] = \"&\" + context[1].replace(/currentPage=\\d{0,}/g, \"\").replace(/&{0,}/, \"\");\r\n");
      out.write("                  }\r\n");
      out.write("               </script>\r\n");
      out.write("\r\n");
      out.write("               <br>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"paging\" align=\"center\">\r\n");
      out.write("                  <!-- 맨 처음으로 -->\r\n");
      out.write("                  <button onclick=\"location.href=context[0] + '?currentPage=1' + context[1]\">&lt;&lt;</button>\r\n");
      out.write("                  <!-- 이전 페이지로 -->\r\n");
      out.write("                  <button onclick=\"location.href=context[0] + '?currentPage=");
      out.print( currentPage - 1 );
      out.write("' + context[1]\" id=\"beforeBtn\">&lt;</button>\r\n");
      out.write("                  <script>\r\n");
      out.write("                  if(");
      out.print( currentPage );
      out.write(" <= 1) {\r\n");
      out.write("                     var before = $('#beforeBtn');\r\n");
      out.write("                     before.attr('disabled', 'true'); //비활성화 시키겠다!\r\n");
      out.write("                  }\r\n");
      out.write("               </script>\r\n");
      out.write("                  <!-- 숫자 목록 버튼 -->\r\n");
      out.write("                  ");
 for(int p = startPage; p <= endPage; p++) { 
      out.write("\r\n");
      out.write("                  ");
 if(p == currentPage) { 
      out.write("\r\n");
      out.write("                  <button id=\"choosen\" disabled>");
      out.print( p );
      out.write("</button>\r\n");
      out.write("                  ");
 } else {  
      out.write("\r\n");
      out.write("                  <button id=\"numBtn\"\r\n");
      out.write("                     onclick=\"location.href=context[0] + '?currentPage=");
      out.print( p );
      out.write("' + context[1]\">");
      out.print( p );
      out.write("</button>\r\n");
      out.write("                  ");
 }  
      out.write("\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <!-- 다음 페이지로 -->\r\n");
      out.write("                  <button onclick=\"location.href=context[0] + '?currentPage=");
      out.print( currentPage + 1 );
      out.write("' + context[1]\" id=\"afterBtn\">&gt;</button>\r\n");
      out.write("                  <script>\r\n");
      out.write("                     if(");
      out.print( currentPage );
      out.write(" >= ");
      out.print( maxPage );
      out.write(") {\r\n");
      out.write("                        var after = $('#afterBtn');\r\n");
      out.write("                        after.attr('disabled', 'true');\r\n");
      out.write("                     }\r\n");
      out.write("                  </script>\r\n");
      out.write("                  <!-- 맨 끝으로 -->\r\n");
      out.write("                  <button onclick=\"location.href=context[0] + '?currentPage=");
      out.print( maxPage );
      out.write("' + context[1]\">&gt;&gt;</button>\r\n");
      out.write("               </div>\r\n");
      out.write("               <script>\r\n");
      out.write("                  $(function(){\r\n");
      out.write("                     $('.item').click(function(){\r\n");
      out.write("                        ");
 if(loginMember != null) { 
      out.write("\r\n");
      out.write("                           var pId = $(this).children().eq(0).val();\r\n");
      out.write("                           location.href='");
      out.print( context );
      out.write("/pdetail.pro?option=0&pId='+ pId;            \r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                           alert('죄송합니다. 회원만 상세보기가 가능합니다!');\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                     });\r\n");
      out.write("                  });\r\n");
      out.write("                  \r\n");
      out.write("                  ");
 if(location1 != null) { 
      out.write("\r\n");
      out.write("                  var location1 = document.getElementById(\"location1\");\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < location1.children.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tif(location1.children[i].value === '");
      out.print( location1 );
      out.write("') {\r\n");
      out.write("\t\t\t\t\t\t\tlocation1.children[i].setAttribute('selected', '');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                  ");
 if(location2 != null) { 
      out.write("\r\n");
      out.write("                  var location2 = document.getElementById(\"location2\");\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < location2.children.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tif(location2.children[i].value === '");
      out.print( location2 );
      out.write("') {\r\n");
      out.write("\t\t\t\t\t\t\tlocation2.children[i].setAttribute('selected', '');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t");
 if(!location1.equals("0")) { 
      out.write("\r\n");
      out.write("\t\t\t\t\tlocation2.removeAttribute('disabled');\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                  ");
 if(location3 != null) { 
      out.write("\r\n");
      out.write("                  var location3 = document.getElementById(\"location3\");\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < location3.children.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tif(location3.children[i].value === '");
      out.print( location3 );
      out.write("') {\r\n");
      out.write("\t\t\t\t\t\t\tlocation3.children[i].setAttribute('selected', '');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t");
 if(!location2.equals("0")) { 
      out.write("\r\n");
      out.write("\t\t\t\t\tlocation3.removeAttribute('disabled');\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                  ");
 if(option != null) { 
      out.write("\r\n");
      out.write("                  var option = document.getElementById(\"categorySearch\");\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < option.children.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tif(option.children[i].value === '");
      out.print( option );
      out.write("') {\r\n");
      out.write("\t\t\t\t\t\t\toption.children[i].setAttribute('selected', '');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                  ");
 if(option2 != null) { 
      out.write("\r\n");
      out.write("                  var option2 = document.getElementById(\"so\");\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < option2.children.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tif(option2.children[i].value === '");
      out.print( option2 );
      out.write("') {\r\n");
      out.write("\t\t\t\t\t\t\toption2.children[i].setAttribute('selected', '');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                  ");
 if(word != null) { 
      out.write("\r\n");
      out.write("                  var word = document.getElementById(\"word\");\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < word.children.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tif(word.children[i].value === '");
      out.print( word );
      out.write("') {\r\n");
      out.write("\t\t\t\t\t\t\tword.children[i].setAttribute('selected', '');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  function sidoChange() {\r\n");
      out.write("                \t var form = document.getElementById('catesearch');\r\n");
      out.write("                \t var location2 = document.getElementById('location2');\r\n");
      out.write("                \t location2.removeAttribute('disabled');\r\n");
      out.write("                \t location2.value = '0';\r\n");
      out.write("                \t var location3 = document.getElementById('location3');\r\n");
      out.write("                \t location3.removeAttribute('disabled');\r\n");
      out.write("                \t location3.value = '0';\r\n");
      out.write("                \t \r\n");
      out.write("                \t //inputData(form);\r\n");
      out.write("                \t \r\n");
      out.write("                 \t form.submit();\r\n");
      out.write("           \r\n");
      out.write("     \t\t\t }\r\n");
      out.write("                  \r\n");
      out.write("                  function sigunguChange() {\r\n");
      out.write("                \t var form = document.getElementById('catesearch');\r\n");
      out.write("                \t var location3 = document.getElementById('location3');\r\n");
      out.write("                \t location3.removeAttribute('disabled');\r\n");
      out.write("                \t location3.value = '0';\r\n");
      out.write("                \t \r\n");
      out.write("                \t //inputData(form);\r\n");
      out.write("                \t \r\n");
      out.write("                  \t form.submit();\r\n");
      out.write("            \r\n");
      out.write("                  }\r\n");
      out.write("                  \r\n");
      out.write("                  function dongChange() {\r\n");
      out.write("                \t var form = document.getElementById('catesearch');\r\n");
      out.write("                \t \r\n");
      out.write("                \t //inputData(form);\r\n");
      out.write("                \t \r\n");
      out.write("                   \t form.submit();\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("                  \r\n");
      out.write("                document.getElementById('searchWord').onclick = function () {\r\n");
      out.write("\t\t\t\t\tsubmitForm();\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                function submitForm() {\r\n");
      out.write("                \tvar form = document.getElementById('catesearch');\r\n");
      out.write("                \t\r\n");
      out.write("                \tinputData(form);\r\n");
      out.write("                \t\r\n");
      out.write("               \t \tform.submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("                \r\n");
      out.write("                function inputData(form) {\r\n");
      out.write("                \tvar so = document.getElementById('so').value;\r\n");
      out.write("                \tvar word = document.getElementById('word').value;\r\n");
      out.write("                \t\r\n");
      out.write("                \tvar input1 = document.createElement('input');\r\n");
      out.write("                \tinput1.setAttribute('name', 'searchOption');\r\n");
      out.write("                \tinput1.setAttribute('type', 'hidden');\r\n");
      out.write("                \tinput1.setAttribute('value', so);\r\n");
      out.write("                \tvar input2 = document.createElement('input');\r\n");
      out.write("                \tinput2.setAttribute('name', 'word');\r\n");
      out.write("                \tinput2.setAttribute('type', 'hidden');\r\n");
      out.write("                \tinput2.setAttribute('value', word);\r\n");
      out.write("                \t\r\n");
      out.write("                \tform.appendChild(input1);\r\n");
      out.write("                \tform.appendChild(input2);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("               </script>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   <div class=\"wrap\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/footer.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t(주) 로켓 대표 KIM LOCKET | 서울 강남구 테헤란로14길 6 남도빌딩 2층 <br>\r\n");
      out.write("   E-mail locket_manaer@locket.co.kr | Tel 02-6952-0337 \r\n");
      out.write("   \r\n");
      out.write("   </footer>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>advertise</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/ad.css\">\r\n");
      out.write("<script src=\"");
      out.print( context );
      out.write("/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("   <aside id=\"advertise\">\r\n");
      out.write("      <a href=\"#header\" id=\"topbt\">맨 위로▲</a>\r\n");
      out.write("      <h2>광고 배너</h2>\r\n");
      out.write("      <a href=\"http://iei.or.kr\" target=\"_blank\">\r\n");
      out.write("         <img id=\"adImg\" src=\"");
      out.print( context );
      out.write("/resources/images/kh.png\">\r\n");
      out.write("         <br>\r\n");
      out.write("         <b>kh정보교육원</b> \r\n");
      out.write("         <br>\r\n");
      out.write("      </a>\r\n");
      out.write("      <br>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <a href=\"http://www.q-net.or.kr/man001.do?gSite=Q\" target=\"_blank\">\r\n");
      out.write("         <img id=\"adImg\" src=\"");
      out.print( context );
      out.write("/resources/images/QNET.JPG\">\r\n");
      out.write("         <br>\r\n");
      out.write("         <b>자격증 접수</b>\r\n");
      out.write("      </a>\r\n");
      out.write("      <br>\r\n");
      out.write("      \r\n");
      out.write("      <br><br>\r\n");
      out.write("   \r\n");
      out.write("      <a href=\"https://www.dataq.or.kr/www/main.do\" target=\"_blank\">\r\n");
      out.write("         <img id=\"adImg\" src=\"");
      out.print( context );
      out.write("/resources/images/KDATA.JPG\">\r\n");
      out.write("         <br>\r\n");
      out.write("         <b>데이터 자격 시험</b>\r\n");
      out.write("      </a>\r\n");
      out.write("      <br>\r\n");
      out.write("   </aside>\r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("      $(function() {\r\n");
      out.write("         adReset();\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      window.onresize = function() {\r\n");
      out.write("        adReset();     \r\n");
      out.write("      };\r\n");
      out.write("      \r\n");
      out.write("      window.onfocus = function() {\r\n");
      out.write("         adReset();\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      function adReset() {\r\n");
      out.write("         var width = window.outerWidth;\r\n");
      out.write("         var ad = document.getElementById(\"advertise\");\r\n");
      out.write("         if(width < 1591) {\r\n");
      out.write("             ad.style.position = \"relative\";\r\n");
      out.write("             ad.style.top = \"-80%\";\r\n");
      out.write("             ad.style.right = \"-15%\";\r\n");
      out.write("           } else {\r\n");
      out.write("             ad.style.position = \"fixed\";\r\n");
      out.write("             ad.style.top = \"30%\";\r\n");
      out.write("             ad.style.right = \"1%\";\r\n");
      out.write("           }        \r\n");
      out.write("      }\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
