/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-11-10 02:37:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sun.corba.se.pept.transport.ContactInfo;
import product.model.vo.Product;
import java.util.ArrayList;
import product.model.vo.Product_File;
import java.io.File;
import member.model.vo.Member;

public final class product_005fupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/common/ad.jsp", Long.valueOf(1604923087294L));
    _jspx_dependants.put("/resources/globalVariable.jsp", Long.valueOf(1604828540617L));
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1604923087459L));
    _jspx_dependants.put("/WEB-INF/views/common/nav.jsp", Long.valueOf(1604923087467L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1604923087451L));
    _jspx_dependants.put("/WEB-INF/views/common/tom.jsp", Long.valueOf(1604923087496L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.sun.corba.se.pept.transport.ContactInfo");
    _jspx_imports_classes.add("product.model.vo.Product");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("product.model.vo.Product_File");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	Product p = (Product)request.getAttribute("product");
	ArrayList<Product_File> pfList = (ArrayList<Product_File>)request.getAttribute("pfList");
	Product_File titleImg = null;
	if(pfList.size() > 0) {
		titleImg = pfList.get(0);
	}
	Product_File img1 = null;
	Product_File img2 = null;
	Product_File img3 = null;
	
	ArrayList<String> locationList = (ArrayList<String>) request.getAttribute("locationList");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>로컬마켓</title>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	String context = request.getContextPath();

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar context = \"");
      out.print( context );
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.print( context );
      out.write("/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<link rel = \"icon\" href = \"");
      out.print( context );
      out.write("/favicon.ico\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/base.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/content-area.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/content.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/product_register.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"wrap\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member)session.getAttribute("loginMember");
	String pImageName = null;
	if(loginMember != null && loginMember.getpImage() != null) {
		File f = new File(loginMember.getpImage());
		pImageName = f.getName();
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id='header'>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print( context );
      out.write("/\"> \r\n");
      out.write("\t\t\t\t<img id='logo-img' alt=\"로컬마켓\" src=\"");
      out.print( context );
      out.write("/resources/images/rocket.png\"></a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print( context );
      out.write("/\"><span id=\"logo-text\">로켓</span></a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t <form action=\"allSearch.all\" method=\"get\" class=\"AllSearchForm\">\r\n");
      out.write("       \t \t<div id=\"header-search\">\r\n");
      out.write("            <input type=\"text\" name=\"word\" placeholder=\"검색어를 입력하세요!\"> \r\n");
      out.write("            <button class=\"glyphicon glyphicon-search\" id=\"AllSearchBtn\"></button>\r\n");
      out.write("         \t</div>\r\n");
      out.write("         </form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t");
 if(loginMember == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"account\">\r\n");
      out.write("\t\t\t\t\t<form action=\"");
      out.print( context );
      out.write("/login.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"id-area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"idInput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" id=\"login\" value=\"로그인\">로그인</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"pw-area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"pwInput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" id=\"signup\" value=\"회원가입\" onclick=\"location.href='");
      out.print( context );
      out.write("/joinForm.do'\">회원가입</button><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" id=\"find\" value=\"ID/PW찾기\" onclick=\"findIDPW();\" style=\"float: right; width: 80px; font-weight:bold; border:none;\">\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"account_info\">\r\n");
      out.write("\t\t\t\t<div id=\"profileArea\">\r\n");
      out.write("\t\t\t\t");
 if(loginMember.getpImage() == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<label id=\"memberIcon\" class=\"glyphicon glyphicon-user\" style=\"top:15px; right: 30px;\"></label>\r\n");
      out.write("\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<img id=\"memberImg\" src=\"");
      out.print( context );
      out.write("/userProfile_uploadFiles/");
      out.print( pImageName );
      out.write("\">\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"membername\">");
      out.print( loginMember.getNickName() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"memberbtn\">\r\n");
      out.write("                  <button id='logoutBtn' onclick=\"location.href='");
      out.print( context );
      out.write("/logout.do'\">로그아웃</button>\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <button id=\"myPageBtn\" onclick=\"location.href='");
      out.print( context );
      out.write("/myPage.do'\">마이페이지</button>\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <button id=\"messageBtn\" onclick=\"location.href='");
      out.print( context );
      out.write("/message.do'\">쪽지함</button>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div id=\"alarm\">\r\n");
      out.write("                  <button class=\"glyphicon glyphicon-bell\" onclick=\"location.href='");
      out.print( context );
      out.write("/receiveP.do'\"></button>\r\n");
      out.write("               </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t");
 if(loginMember != null) { 
      out.write("\r\n");
      out.write("\t\t\tvar openProfile = function(closeCallback) {\r\n");
      out.write("\t\t\t    var win = window.open('setProfileImgForm.do', 'setProfileImgForm', 'width=500, height=450');\r\n");
      out.write("\t\t\t    var interval = window.setInterval(function() {\r\n");
      out.write("\t\t\t        try {\r\n");
      out.write("\t\t\t            if (win == null || win.closed) {\r\n");
      out.write("\t\t\t                window.clearInterval(interval);\r\n");
      out.write("\t\t\t                closeCallback(win);\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        catch (e) {\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    }, 1000);\r\n");
      out.write("\t\t\t    return win;\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"profileArea\").onclick = function() {\r\n");
      out.write("\t\t\t\topenProfile(function(win) {\r\n");
      out.write("\t\t\t\t\tlocation.reload(true);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t");
 } else { 
      out.write("\r\n");
      out.write("      \tfunction findIDPW() {\r\n");
      out.write("      \t\twindow.open('findIDPWForm.do', 'findIDPWForm', 'width=500, height=135');\r\n");
      out.write("\t\t}\r\n");
      out.write("      \r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("      <div id=\"content-area\">\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>nav</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/nav.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"nav\">\r\n");
      out.write("   \r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("            \r\n");
      out.write("            <!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("            <div id=\"menu-area\">\r\n");
      out.write("               <ul class=\"out-menu\">\r\n");
      out.write("                  <label class=\"glyphicon glyphicon-camera\"><div>중고물품</div></label>\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/list.pro'\">중고 물품보기</button></li>\r\n");
      out.write("                  ");
 if(loginMember != null) { 
      out.write("\r\n");
      out.write("                     <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/registerForm.pro'\">중고 물품등록</button></li>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("               <ul class=\"out-menu\">\r\n");
      out.write("                  <label class=\"glyphicon glyphicon-tag\"><div>공동구매</div></label>\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/groupList.do'\">공동구매 목록조회</button></li>\r\n");
      out.write("                  ");
 if(loginMember != null && loginMember.getRankCode() == 99) { 
      out.write("\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/groupWriteForm.do'\">공동구매 물품등록</button></li> \r\n");
      out.write("\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("               <ul class=\"out-menu menuBtn\" onclick=\"location.href='");
      out.print( context );
      out.write("/boardList.do'\">\r\n");
      out.write("                  <label class=\"glyphicon glyphicon-list\" class=\"menuBtn\"><div class=\"menuBtn\">자유게시판</div></label>\r\n");
      out.write("               </ul>\r\n");
      out.write("               ");
 if(loginMember != null && loginMember.getRankCode() == 99) { 
      out.write("\r\n");
      out.write("               <ul class=\"out-menu\">\r\n");
      out.write("                  <label class=\"glyphicon glyphicon-lock\"><div>관리자</div></label>\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/managerInfo.do'\">회원 정보 관리</li>\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/managerreport.do'\">신고 목록 관리</li>\r\n");
      out.write("               </ul>\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Top of this Month</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/tom.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"tom\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<b>이달의 로켓왕!</b>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table id=\"tom-table\">\r\n");
      out.write("\t\t\t<tr id=\"table-head\">\r\n");
      out.write("\t\t\t\t<th>No.</th>\r\n");
      out.write("\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t<th>거래 수</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<div id=\"loading\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print( context );
      out.write("/resources/images/loading.gif\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: 'topOfMonth.do',\r\n");
      out.write("\t\ttype: 'post',\r\n");
      out.write("\t\tdata: {first: 1, last: 3},\r\n");
      out.write("\t\tsuccess: function(data) {\t\r\n");
      out.write("\t\t\tvar table = document.getElementById(\"tom-table\");\r\n");
      out.write("\t\t\tfor(var i in data) {\r\n");
      out.write("\t\t\t\tvar tr = document.createElement(\"tr\");\r\n");
      out.write("\t\t\t\tvar td1 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\ttd1.innerHTML = data[i].rank;\r\n");
      out.write("\t\t\t\tvar td2 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\ttd2.innerHTML = data[i].nickname;\r\n");
      out.write("\t\t\t\tvar td3 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\ttd3.innerHTML = data[i].count;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttr.appendChild(td1);\r\n");
      out.write("\t\t\t\ttr.appendChild(td2);\r\n");
      out.write("\t\t\t\ttr.appendChild(td3);\r\n");
      out.write("\t\t\t\ttable.appendChild(tr);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('#tom-table').show();\r\n");
      out.write("\t\t\t$('#loading').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            <!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <script>\r\n");
      out.write("            $('.out-menu').click(function(){\r\n");
      out.write("               $(this).children().next().slideToggle();\r\n");
      out.write("            });\r\n");
      out.write("         </script>\r\n");
      out.write("         \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("         <div id =\"content\">\r\n");
      out.write("         <br>\r\n");
      out.write("         \r\n");
      out.write("        <h1>중고 물품수정</h1>\r\n");
      out.write("        \r\n");
      out.write("        <br><br>\r\n");
      out.write("\t\t<!-- 파일업로드를 위해 enctype을 지정해줘야 된다. -->\r\n");
      out.write("\t\t<form action=\"");
      out.print( request.getContextPath() );
      out.write("/productUpdate.do\" method=\"post\" encType=\"multipart/form-data\" id=\"updateProduct\"><!-- 파일올리는 거기 때문에 -->\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"pId\" value=\"");
      out.print( p.getProductId() );
      out.write("\">\r\n");
      out.write("\t\t\t<div class=\"insertArea\">\r\n");
      out.write("\t\t\t\t<table id=\"insertThumbTable\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("                  <th>지역</th>\r\n");
      out.write("                  <td colspan=\"3\">\r\n");
      out.write("                     <select name=\"location1\" id=\"location1\" onchange=\"sidoChange();\">\r\n");
      out.write("                     <option value=\"0\">시/도</option>\r\n");
      out.write("                     ");
 for(String location : locationList) { 
      out.write("\r\n");
      out.write("                     <option>");
      out.print( location );
      out.write("</option>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                     </select>\r\n");
      out.write("                     <select name=\"location2\" id=\"location2\" onchange=\"sigunguChange();\" disabled>\r\n");
      out.write("                     \t<option value=\"0\">시/군/구</option>\r\n");
      out.write("                     </select>\r\n");
      out.write("                     <select name=\"location3\" id=\"location3\" disabled>\r\n");
      out.write("                     \t<option value=\"0\">동</option>\r\n");
      out.write("                     </select>\r\n");
      out.write("                  </td>\r\n");
      out.write("               \t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>카테고리</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"category\" name=\"category\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"의류\">의류</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"패션잡화\">패션잡화</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"디지털가전\">디지털가전</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"뷰티/미용\">뷰티/미용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"유아/출산\">유아/출산</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"기타\">기타</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"100px\">물품명</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" id=\"title1\" name=\"title\" value=\"");
      out.print( p.getTitle() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>판매 가격</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" id=\"price1\" name=\"price\" placeholder=\"&#8361 가격 입력\" value=\"");
      out.print( p.getPrice() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>상품  상태</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type =\"radio\" name=\"condition\" value=\"미개봉\"> 미개봉</td>\r\n");
      out.write("\t\t\t\t        <td><input type =\"radio\" name=\"condition\" value=\"거의 새 것\"> 거의 새 것</td>\r\n");
      out.write("\t\t\t\t        <td><input type =\"radio\" name=\"condition\" value=\"사용감 있음\"> 사용감 있음</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>배송 방법</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type =\"radio\" name=\"delivery\" value=\"직거래\"> 직거래</td>\r\n");
      out.write("\t\t\t\t        <td><input type =\"radio\" name=\"delivery\" value=\"택배거래\"> 택배거래</td>\r\n");
      out.write("\t\t\t\t        <td><input type =\"radio\" name=\"delivery\" value=\"상관없음\"> 상관없음</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td> </td><td> </td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>대표 이미지</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"titleImgArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"titleImg\" width=\"525\" height=\"300\" ");
      out.print( titleImg == null ? "" : "src='"  + context + "/product_uploadFiles/" + titleImg.getChangeName() + "'"  );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>추가 사진</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"contentImgArea1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"contentImg1\" width=\"167\" height=\"100\" ");
      out.print( pfList.size() <= 1 ? "" : pfList.get(1) == null ? "" : "src='"  + context + "/product_uploadFiles/" + pfList.get(1).getChangeName() + "'"  );
      out.write("> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"contentImgArea2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"contentImg2\" width=\"167\" height=\"100\" ");
      out.print( pfList.size() <= 2 ? "" : pfList.get(1) == null ? "" : "src='"  + context + "/product_uploadFiles/" + pfList.get(2).getChangeName() + "'"  );
      out.write("> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"contentImgArea3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"contentImg3\" width=\"167\" height=\"100\" ");
      out.print( pfList.size() <= 3 ? "" : pfList.get(1) == null ? "" : "src='"  + context + "/product_uploadFiles/" + pfList.get(3).getChangeName() + "'"  );
      out.write("> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>물품 설명</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"><textarea id=\"pContent\" name=\"explain\" rows=\"10\" cols=\"80\" \r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"게시글 내용을 작성해주세요. (가품 및 판매금지품목은 게시가 제한됩니다.)\" style=\"resize:none;\">");
      out.print( p.getExplain() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"btnArea\">\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" id=\"cancelBtn\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/list.pro'\" value=\"목록으로\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" id=\"obj\" value=\"상품수정\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 파일 업로드 하는 부분 -->\r\n");
      out.write("\t\t\t\t<div id=\"fileArea\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg1\" multiple=\"multiple\" name=\"titleImg\" onchange=\"LoadImg(this,1)\" accept=\"image/*\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg2\" multiple=\"multiple\" name=\"thumbnailImg2\" onchange=\"LoadImg(this,2)\" accept=\"image/*\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg3\" multiple=\"multiple\" name=\"thumbnailImg3\" onchange=\"LoadImg(this,3)\" accept=\"image/*\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg4\" multiple=\"multiple\" name=\"thumbnailImg4\" onchange=\"LoadImg(this,4)\" accept=\"image/*\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tvar location1 = document.getElementById(\"location1\");\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < location1.children.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tif(location1.children[i].value == '");
      out.print( p.getLocation1() );
      out.write("') {\r\n");
      out.write("\t\t\t\t\t\t\tlocation1.children[i].setAttribute('selected', '');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsidoChange();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsetTimeout(setLocation2, 500);\r\n");
      out.write("\t\t\t\t\tfunction setLocation2() {\r\n");
      out.write("\t\t\t\t\t\tvar location2 = document.getElementById(\"location2\");\r\n");
      out.write("\t\t\t\t\t\tfor(var i = 0; i < location2.children.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\tif(location2.children[i].value == '");
      out.print( p.getLocation2() );
      out.write("') {\r\n");
      out.write("\t\t\t\t\t\t\t\tlocation2.children[i].setAttribute('selected', '');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tsigunguChange();\r\n");
      out.write("\t\t\t\t\t\tsetTimeout(setLoaction3, 100);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfunction setLoaction3() {\r\n");
      out.write("\t\t\t\t\t\tvar location3 = document.getElementById(\"location3\");\r\n");
      out.write("\t\t\t\t\t\tfor(var i = 0; i < location3.children.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\tif(location3.children[i].value == '");
      out.print( p.getLocation3() );
      out.write("') {\r\n");
      out.write("\t\t\t\t\t\t\t\tlocation3.children[i].setAttribute('selected', '');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar category = document.getElementById(\"category\");\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < category.children.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tif(category.children[i].value === '");
      out.print( p.getCategory() );
      out.write("') { \r\n");
      out.write("\t\t\t\t\t\t\tcategory.children[i].setAttribute('selected', '');\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar condition = document.getElementsByName('condition');\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < condition.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tif(condition[i].value == '");
      out.print( p.getCondition() );
      out.write("') {\r\n");
      out.write("\t\t\t\t\t\t\tcondition[i].setAttribute('checked', '');\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar delivery = document.getElementsByName('delivery');\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < delivery.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tif(delivery[i].value == '");
      out.print( p.getDelivery() );
      out.write("') {\r\n");
      out.write("\t\t\t\t\t\t\tdelivery[i].setAttribute('checked', '');\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// 내용 작성 부분의 공간을 클릭할 때 파일 첨부 창이 뜨도록 설정하는 함수\r\n");
      out.write("\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#fileArea\").hide();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#titleImgArea\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg1\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#contentImgArea1\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg2\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#contentImgArea2\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg3\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#contentImgArea3\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg4\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar check1 = false;\r\n");
      out.write("\t\t\t\t\tvar check2 = false;\r\n");
      out.write("\t\t\t\t\tvar check3 = false;\r\n");
      out.write("\t\t\t\t\tvar check4 = false;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// 각각의 영역에 파일을 첨부 했을 경우 미리 보기가 가능하도록 하는 함수\r\n");
      out.write("\t\t\t\t\tfunction LoadImg(value, num){\r\n");
      out.write("\t\t\t\t\t\tif(value.files && value.files[0]){\r\n");
      out.write("\t\t\t\t\t\t\tvar reader = new FileReader();\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tvar form = document.getElementById('updateProduct');\r\n");
      out.write("\t\t\t\t\t\t\tvar input = document.createElement('input');\r\n");
      out.write("\t\t\t\t\t\t\tinput.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("\t\t\t\t\t\t\tinput.setAttribute(\"name\", \"changeFile\");\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\treader.onload = function(e){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tswitch(num){\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 1: \r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#titleImg\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(!check1) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print( titleImg == null ? "" : "input.setAttribute('value', '" + titleImg.getPfId() + "');" );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tform.appendChild(input);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcheck1 = true;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 2:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg1\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(!check2) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print( pfList.size() <= 1 ? "" : pfList.get(1) == null ? "" : "input.setAttribute('value', '" + pfList.get(1).getPfId() + "'); form.appendChild(input);" );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcheck2 = true;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 3: \r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg2\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(!check3) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print( pfList.size() <= 2 ? "" : pfList.get(2) == null ? "" : "input.setAttribute('value', '" + pfList.get(2).getPfId() + "'); form.appendChild(input);" );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcheck3 = true;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 4:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg3\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(!check4) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print( pfList.size() <= 3 ? "" : pfList.get(3) == null ? "" : "input.setAttribute('value', '" + pfList.get(3).getPfId() + "'); form.appendChild(input);" );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcheck4 = true;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\treader.readAsDataURL(value.files[0]);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfunction productSubmit() {\r\n");
      out.write("\t\t                   var title = document.getElementById(\"title1\").value;\r\n");
      out.write("\t\t                   var price = document.getElementById(\"price1\").value;                   \r\n");
      out.write("\t\t                    var content = document.getElementById(\"pContent\").value;                    \r\n");
      out.write("\t\t                    var condition = document.getElementsByName('condition');\r\n");
      out.write("\t\t                    var delivery = document.getElementsByName('delivery');\r\n");
      out.write("\t\t                    var image = document.getElementById(\"titleImg\").src;\r\n");
      out.write("\t\t                    var cate = document.getElementsByName('category').value;\r\n");
      out.write("\r\n");
      out.write("\t\t                    if(title == \"\") {\r\n");
      out.write("\t\t                       alert(\"제목을 입력하세요\");\r\n");
      out.write("\t\t                       return;\r\n");
      out.write("\t\t                    } else if(content == \"\") {\r\n");
      out.write("\t\t                      alert(\"내용을 입력하세요\");\r\n");
      out.write("\t\t                      return;\r\n");
      out.write("\t\t                   } else if(price == \"\") {\r\n");
      out.write("\t\t                      alert(\"가격을 입력하세요\");\r\n");
      out.write("\t\t                      return;\r\n");
      out.write("\t\t                    } else if(image == \"\") {\r\n");
      out.write("\t\t                     alert(\"사진을 최소 1장 이상 등록해주세요.\");\r\n");
      out.write("\t\t                     return;\r\n");
      out.write("\t\t                   } else if(cate == \"\") {\r\n");
      out.write("\t\t                    alert(\"카테고리를 선택해주세요.\");\r\n");
      out.write("\t\t                    return;\r\n");
      out.write("\t\t                  }\r\n");
      out.write("\t\t                    \r\n");
      out.write("\t\t                    //////상태체크 /////\r\n");
      out.write("\t\t                    var sel_con = null;\r\n");
      out.write("\t\t                  for(var i=0; i < condition.length; i++){\r\n");
      out.write("\t\t                     if(condition[i].checked == true){ \r\n");
      out.write("\t\t                        sel_con = condition[i].value;\r\n");
      out.write("\t\t                     }\r\n");
      out.write("\t\t                  }\r\n");
      out.write("\t\t                  if(sel_con == null){\r\n");
      out.write("\t\t                       alert(\"상품 상태를 선택하세요.\"); \r\n");
      out.write("\t\t                     return false;\r\n");
      out.write("\t\t                  }\r\n");
      out.write("\t\t                  //////배송체크 /////\r\n");
      out.write("\t\t                  var sel_del = null;\r\n");
      out.write("\t\t                  for(var i=0; i < delivery.length; i++){\r\n");
      out.write("\t\t                     if(delivery[i].checked == true){ \r\n");
      out.write("\t\t                        sel_del = delivery[i].value;\r\n");
      out.write("\t\t                     }\r\n");
      out.write("\t\t                  }\r\n");
      out.write("\t\t                  if(sel_del == null){\r\n");
      out.write("\t\t                       alert(\"배송 방법을 선택하세요.\"); \r\n");
      out.write("\t\t                     return false;\r\n");
      out.write("\t\t                  }\r\n");
      out.write("\t\t                  \r\n");
      out.write("\t\t                  var regexp = /^[0-9]*$/\r\n");
      out.write("\t\t                  v = $('#price1').val();\r\n");
      out.write("\t\t                  if(!regexp.test(v)) {\r\n");
      out.write("\t\t                        alert(\"가격은 숫자만 입력하세요\");\r\n");
      out.write("\t\t                      $('#price1').val(v.replace(regexp,''));\r\n");
      out.write("\t\t                      return false;\r\n");
      out.write("\t\t                  }\r\n");
      out.write("\t\t                     \r\n");
      out.write("\t\t                      document.getElementById('updateProduct').submit();            \r\n");
      out.write("\t\t               }   \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfunction sidoChange() {\r\n");
      out.write("\t\t            \t var location1 = document.getElementById('location1').value;\r\n");
      out.write("\t\t            \t var location2 = document.getElementById('location2');\r\n");
      out.write("\t\t            \t var location3 = document.getElementById('location3');\r\n");
      out.write("\t\t            \t location2.innerHTML = \"\";\r\n");
      out.write("\t\t            \t location3.innerHTML = \"\";\r\n");
      out.write("\t\t            \t if(location1 != '0') {\r\n");
      out.write("\t\t\t            \t $.ajax({\r\n");
      out.write("\t\t\t            \t\t url: 'addr.do',\r\n");
      out.write("\t\t\t            \t\t type: 'get',\r\n");
      out.write("\t\t\t            \t\t data: {sido: location1},\r\n");
      out.write("\t\t\t            \t\t success: function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor(var i in data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar option = document.createElement('option');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\toption.innerHTML = data[i];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlocation2.appendChild(option);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsigunguChange();\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlocation2.removeAttribute('disabled');\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t            \t });\r\n");
      out.write("\t\t            \t } else {\r\n");
      out.write("\t\t            \t\t location2.setAttribute('disabled', \"disabled\");\r\n");
      out.write("\t\t            \t\t location3.setAttribute('disabled', \"disabled\");\r\n");
      out.write("\t\t            \t\t location2.innerHTML = \"<option value='0'>시/군/구</option>\";\r\n");
      out.write("\t\t            \t\t location3.innerHTML = \"<option value='0'>동</option>\";\r\n");
      out.write("\t\t            \t }\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t             function sigunguChange() {\r\n");
      out.write("\t\t            \t var location1 = document.getElementById('location1').value;\r\n");
      out.write("\t\t            \t var location2 = document.getElementById('location2');\r\n");
      out.write("\t\t            \t var location3 = document.getElementById('location3');\r\n");
      out.write("\t\t            \t location3.innerHTML = \"\";\r\n");
      out.write("\t\t            \t if(location2 != '0') {\r\n");
      out.write("\t\t\t            \t $.ajax({\r\n");
      out.write("\t\t\t            \t\t url: 'addr.do',\r\n");
      out.write("\t\t\t            \t\t type: 'get',\r\n");
      out.write("\t\t\t            \t\t data: {sido: location1, sigungu: location2.value},\r\n");
      out.write("\t\t\t            \t\t success: function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor(var i in data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar option = document.createElement('option');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\toption.innerHTML = data[i];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlocation3.appendChild(option);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlocation3.removeAttribute('disabled');\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t            \t });\r\n");
      out.write("\t\t            \t } else {\r\n");
      out.write("\t\t            \t\t location3.setAttribute('disabled', \"disabled\");\r\n");
      out.write("\t\t            \t\t location3.innerHTML = \"<option value='0'>동</option>\";\r\n");
      out.write("\t\t            \t\t \r\n");
      out.write("\t\t            \t }\r\n");
      out.write("\t\t             }\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   <div class=\"wrap\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/footer.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t(주) 로켓 대표 KIM LOCKET | 서울 강남구 테헤란로14길 6 남도빌딩 2층 <br>\r\n");
      out.write("   E-mail locket_manaer@locket.co.kr | Tel 02-6952-0337 \r\n");
      out.write("   \r\n");
      out.write("   </footer>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>advertise</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/ad.css\">\r\n");
      out.write("<script src=\"");
      out.print( context );
      out.write("/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("   <aside id=\"advertise\">\r\n");
      out.write("      <a href=\"#header\" id=\"topbt\">맨 위로▲</a>\r\n");
      out.write("      <h2>광고 배너</h2>\r\n");
      out.write("      <a href=\"http://iei.or.kr\" target=\"_blank\">\r\n");
      out.write("         <img id=\"adImg\" src=\"");
      out.print( context );
      out.write("/resources/images/kh.png\">\r\n");
      out.write("         <br>\r\n");
      out.write("         <b>kh정보교육원</b> \r\n");
      out.write("         <br>\r\n");
      out.write("      </a>\r\n");
      out.write("      <br>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <a href=\"http://www.q-net.or.kr/man001.do?gSite=Q\" target=\"_blank\">\r\n");
      out.write("         <img id=\"adImg\" src=\"");
      out.print( context );
      out.write("/resources/images/QNET.JPG\">\r\n");
      out.write("         <br>\r\n");
      out.write("         <b>자격증 접수</b>\r\n");
      out.write("      </a>\r\n");
      out.write("      <br>\r\n");
      out.write("      \r\n");
      out.write("      <br><br>\r\n");
      out.write("   \r\n");
      out.write("      <a href=\"https://www.dataq.or.kr/www/main.do\" target=\"_blank\">\r\n");
      out.write("         <img id=\"adImg\" src=\"");
      out.print( context );
      out.write("/resources/images/KDATA.JPG\">\r\n");
      out.write("         <br>\r\n");
      out.write("         <b>데이터 자격 시험</b>\r\n");
      out.write("      </a>\r\n");
      out.write("      <br>\r\n");
      out.write("   </aside>\r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("      $(function() {\r\n");
      out.write("         adReset();\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      window.onresize = function() {\r\n");
      out.write("        adReset();     \r\n");
      out.write("      };\r\n");
      out.write("      \r\n");
      out.write("      window.onfocus = function() {\r\n");
      out.write("         adReset();\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      function adReset() {\r\n");
      out.write("         var width = window.outerWidth;\r\n");
      out.write("         var ad = document.getElementById(\"advertise\");\r\n");
      out.write("         if(width < 1591) {\r\n");
      out.write("             ad.style.position = \"relative\";\r\n");
      out.write("             ad.style.top = \"-80%\";\r\n");
      out.write("             ad.style.right = \"-15%\";\r\n");
      out.write("           } else {\r\n");
      out.write("             ad.style.position = \"fixed\";\r\n");
      out.write("             ad.style.top = \"30%\";\r\n");
      out.write("             ad.style.right = \"1%\";\r\n");
      out.write("           }        \r\n");
      out.write("      }\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
