/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-10-12 17:28:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class product_005fregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/common/ad.jsp", Long.valueOf(1602507400928L));
    _jspx_dependants.put("/resources/globalVariable.jsp", Long.valueOf(1602507391775L));
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1602507400973L));
    _jspx_dependants.put("/WEB-INF/views/common/nav.jsp", Long.valueOf(1602507400983L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1602507400943L));
    _jspx_dependants.put("/WEB-INF/views/common/search.jsp", Long.valueOf(1602507400994L));
    _jspx_dependants.put("/WEB-INF/views/common/tom.jsp", Long.valueOf(1602507401005L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>로컬마켓</title>\r\n");
      out.write('\r');
      out.write('\n');

	String context = request.getContextPath();

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar context = \"");
      out.print( context );
      out.write("\";\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(context);
      out.write("/resources/css/base.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(context);
      out.write("/resources/css/content-area.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(context);
      out.write("/resources/css/content.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(context);
      out.write("/resources/css/product_register.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"wrap\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member)session.getAttribute("loginMember");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id='header'>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print( context );
      out.write("/\"> \r\n");
      out.write("\t\t\t\t<img id='logo-img' alt=\"로컬마켓\" src=\"");
      out.print( context );
      out.write("/resources/images/rocket.png\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<div id=\"header-text\">\r\n");
      out.write("\t\t\t\t<span>로켓</span> 환영합니다 로켓입니다!\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
 if(loginMember == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"account\">\r\n");
      out.write("\t\t\t\t\t<form action=\"");
      out.print( context );
      out.write("/login.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"id-area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"idInput\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"pw-area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"pwInput\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"account-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"로그인\"> <br> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" id=\"signup\" value=\"회원가입\" onclick=\"location.href='");
      out.print( context );
      out.write("/joinForm.do'\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"account_info\">\r\n");
      out.write("\t\t\t\t\t");
 if(loginMember.getpImage() == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"프로필 사진\" src=\"");
      out.print( context );
      out.write("/resources/images/rocket.png\">\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"프로필 사진\" src=\"\">\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"membername\">");
      out.print( loginMember.getNickName() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"memberbtn\">\r\n");
      out.write("\t\t\t\t\t\t<button id='logoutBtn' onclick=\"location.href='");
      out.print( context );
      out.write("/logout.do'\">로그아웃</button>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"myPageBtn\">마이페이지</button>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"messageBtn\">쪽지함</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("      <div id=\"content-area\">\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>nav</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/nav.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"nav\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>search</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/search.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"search-area\">\r\n");
      out.write("\t\t<form action=\"\" method=\"get\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"search\" id=\"search\" size=\"15\"> \r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"검색\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t\t<div id=\"menu-area\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"out-menu\">\r\n");
      out.write("\t\t\t\t\t\t<div>중고물품</div>\r\n");
      out.write("\t\t\t\t\t\t<li>중고 물품보기</li>\r\n");
      out.write("\t\t\t\t\t\t<li>중고 물품등록</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"out-menu\">\r\n");
      out.write("\t\t\t\t\t\t<div>공동구매</div>\r\n");
      out.write("\t\t\t\t\t\t<li>공동구매 목록조회</li>\r\n");
      out.write("\t\t\t\t\t\t<li>공동구매 캘린더</li>\r\n");
      out.write("\t\t\t\t\t\t<li>공동구매 물품등록</li>\r\n");
      out.write("\t\t\t\t\t\t<li>입금 확인 조회</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"out-menu\">\r\n");
      out.write("\t\t\t\t\t\t<div>자유게시판</div>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"out-menu\">\r\n");
      out.write("\t\t\t\t\t\t<div>관리자</div>\r\n");
      out.write("\t\t\t\t\t\t<li>회원 정보 관리</li>\r\n");
      out.write("\t\t\t\t\t\t<li>신고 목록 관리</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Top of this Month</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/tom.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"tom\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<b>이달의 로켓왕!</b>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<table id=\"tom-table\">\r\n");
      out.write("\t\t\t<tr id=\"table-head\">\r\n");
      out.write("\t\t\t\t<th>No.</th>\r\n");
      out.write("\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t<th>거래 수</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t<td>김로켓</td>\r\n");
      out.write("\t\t\t\t<td>16</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t\t<td>박마켓</td>\r\n");
      out.write("\t\t\t\t<td>14</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <h1>중고물품 등록</h1><hr><br>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"wrap\">\r\n");
      out.write("   <form>\r\n");
      out.write("      <table>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td rowspan = 4>\r\n");
      out.write("            <select>\r\n");
      out.write("               <option value=\"categorysel\" id = \"categorysel\">카테고리를 선택해 주세요.</option>\r\n");
      out.write("               <option value=\"clothes\" id = \"clothes\">의류</option>\r\n");
      out.write("               <option value=\"furniture\" id = \"furniture\">가구</option>\r\n");
      out.write("               <option value=\"shoes\" id = \"shoes\">신발</option>\r\n");
      out.write("               <option value=\"computer\" id = \"computer\">컴퓨터</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            </td>\r\n");
      out.write("            \r\n");
      out.write("            <td>\r\n");
      out.write("            <h3>제목</h3>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <tr>\r\n");
      out.write("            <td><input  type =\"text\" id = title placeholder = \"제목을 입력하세요\"  ></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <tr>\r\n");
      out.write("            <td><h3>판매가격</h3></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td><input type =\"text\" id= price placeholder = \"가격을 입력하세요\">원</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         \r\n");
      out.write("      </table>\r\n");
      out.write("      </div>\r\n");
      out.write("            <input type=\"file\" name=\"profile_pt\" id=\"profile_pt\" onchange=\"previewImage(this,'View_area')\"><br>\r\n");
      out.write("         <div id='View_area'></div>\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("         <h3>상품 상태</h3>\r\n");
      out.write("         <input type =\"radio\" > 미개봉<br>\r\n");
      out.write("         <input type =\"radio\" > 거의 새 것<br>\r\n");
      out.write("         <input type =\"radio\" > 사용감 있음<br>\r\n");
      out.write("         \r\n");
      out.write("         <h3>배송 방법</h3>\r\n");
      out.write("         <input type =\"radio\" > 직거래<br>\r\n");
      out.write("         <input type =\"radio\" > 택배거래<br>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <h3>판매자 정보</h3>\r\n");
      out.write("         <input type =\"text\" placeholder = \"전화번호를 입력하세요.\"><br><br><br>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <input type =\"file\" name=\"file\"  accept=\".JPEG, .PNG\" multiple>\r\n");
      out.write("         \r\n");
      out.write("         <h3>상품 상세내용</h3>\r\n");
      out.write("         <textArea rows=\"30\" cols = \"80\" placeholder =\"내용을입력해주세요\"></textArea>\r\n");
      out.write("         \r\n");
      out.write("         <br>\r\n");
      out.write("         <div id = \"selbt\">\r\n");
      out.write("         <input type = \"button\" id = cancel value = \"취소\">\r\n");
      out.write("         <input type = \"button\" id = register value = \"물품등록\">\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("   </form>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("   function previewImage(targetObj, View_area) {\r\n");
      out.write("      var preview = document.getElementById(View_area); \r\n");
      out.write("      var ua = window.navigator.userAgent;\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("      if (ua.indexOf(\"MSIE\") > -1) {\r\n");
      out.write("         targetObj.select();\r\n");
      out.write("         try {\r\n");
      out.write("            var src = document.selection.createRange().text; // get file full path(IE9, IE10에서 사용 불가)\r\n");
      out.write("            var ie_preview_error = document.getElementById(\"ie_preview_error_\" + View_area);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            if (ie_preview_error) {\r\n");
      out.write("               preview.removeChild(ie_preview_error); //error가 있으면 delete\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            var img = document.getElementById(View_area); //이미지가 뿌려질 곳\r\n");
      out.write("\r\n");
      out.write("            //이미지 로딩, sizingMethod는 div에 맞춰서 사이즈를 자동조절 하는 역할\r\n");
      out.write("            img.style.filter = \"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='\"+src+\"', sizingMethod='scale')\";\r\n");
      out.write("         } catch (e) {\r\n");
      out.write("            if (!document.getElementById(\"ie_preview_error_\" + View_area)) {\r\n");
      out.write("               var info = document.createElement(\"<p>\");\r\n");
      out.write("               info.id = \"ie_preview_error_\" + View_area;\r\n");
      out.write("               info.innerHTML = e.name;\r\n");
      out.write("               preview.insertBefore(info, null);\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("     //ie가 아닐때(크롬, 사파리, FF)\r\n");
      out.write("      } else {\r\n");
      out.write("         var files = targetObj.files;\r\n");
      out.write("         for ( var i = 0; i < files.length; i++) {\r\n");
      out.write("            var file = files[i];\r\n");
      out.write("            var imageType = /image.*/; //이미지 파일일경우만.. 뿌려준다.\r\n");
      out.write("            if (!file.type.match(imageType))\r\n");
      out.write("               continue;\r\n");
      out.write("            var prevImg = document.getElementById(\"prev_\" + View_area); //이전에 미리보기가 있다면 삭제\r\n");
      out.write("            if (prevImg) {\r\n");
      out.write("               preview.removeChild(prevImg);\r\n");
      out.write("            }\r\n");
      out.write("            var img = document.createElement(\"img\"); \r\n");
      out.write("            img.id = \"prev_\" + View_area;\r\n");
      out.write("            img.classList.add(\"obj\");\r\n");
      out.write("            img.file = file;\r\n");
      out.write("            img.style.width = '200px'; \r\n");
      out.write("            img.style.height = '200px';\r\n");
      out.write("            preview.appendChild(img);\r\n");
      out.write("            if (window.FileReader) { // FireFox, Chrome, Opera 확인.\r\n");
      out.write("               var reader = new FileReader();\r\n");
      out.write("               reader.onloadend = (function(aImg) {\r\n");
      out.write("                  return function(e) {\r\n");
      out.write("                     aImg.src = e.target.result;\r\n");
      out.write("                  };\r\n");
      out.write("               })(img);\r\n");
      out.write("               reader.readAsDataURL(file);\r\n");
      out.write("            } else { // safari is not supported FileReader\r\n");
      out.write("               //alert('not supported FileReader');\r\n");
      out.write("               if (!document.getElementById(\"sfr_preview_error_\"\r\n");
      out.write("                     + View_area)) {\r\n");
      out.write("                  var info = document.createElement(\"p\");\r\n");
      out.write("                  info.id = \"sfr_preview_error_\" + View_area;\r\n");
      out.write("                  info.innerHTML = \"not supported FileReader\";\r\n");
      out.write("                  preview.insertBefore(info, null);\r\n");
      out.write("               }\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"wrap\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/footer.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer> 하단 </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>advertise</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/ad.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<aside id=\"advertise\">\r\n");
      out.write("\t\t<h3>광고 배너 입니다.</h3>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<a href=\"http://iei.or.kr\" target=\"_blank\">\r\n");
      out.write("\t\t\t<img id=\"adImg\" src=\"");
      out.print( context );
      out.write("/resources/images/kh.png\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<b>kh정보교육원</b>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<a href=\"http://nike.com\" target=\"_blank\">\r\n");
      out.write("\t\t\t<img id=\"adImg\" src=\"");
      out.print( context );
      out.write("/resources/images/ad1.jpg\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<b>에어 조던 1 로우</b>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<em>119,000</em>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<a href=\"http://nike.com\" target=\"_blank\">\r\n");
      out.write("\t\t\t<img id=\"adImg\" src=\"");
      out.print( context );
      out.write("/resources/images/ad1.jpg\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<b>에어 조던 1 로우</b>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<em>119,000</em>\r\n");
      out.write("\t</aside>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
