/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-10-12 06:08:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/common/ad.jsp", Long.valueOf(1602258723224L));
    _jspx_dependants.put("/resources/globalVariable.jsp", Long.valueOf(1602400317031L));
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1602402211209L));
    _jspx_dependants.put("/WEB-INF/views/common/nav.jsp", Long.valueOf(1602251573844L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1602251104318L));
    _jspx_dependants.put("/WEB-INF/views/common/search.jsp", Long.valueOf(1602251112993L));
    _jspx_dependants.put("/WEB-INF/views/common/tom.jsp", Long.valueOf(1602251098592L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>로컬마켓</title>\r\n");
      out.write('\r');
      out.write('\n');

	String context = request.getContextPath();

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar context = \"");
      out.print( context );
      out.write("\";\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/base.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/content-area.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/content.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/join.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member)session.getAttribute("loginMember");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id='header'>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print( context );
      out.write("/\"> \r\n");
      out.write("\t\t\t\t<img id='logo-img' alt=\"로컬마켓\" src=\"");
      out.print( context );
      out.write("/resources/images/rocket.png\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<div id=\"header-text\">\r\n");
      out.write("\t\t\t\t<span>로켓</span> 환영합니다 로켓입니다!\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
 if(loginMember == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"account\">\r\n");
      out.write("\t\t\t\t\t<form action=\"");
      out.print( context );
      out.write("/login.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"id-area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"idInput\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"pw-area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"pwInput\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"account-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"로그인\"> <br> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" id=\"signup\" value=\"회원가입\" onclick=\"location.href='");
      out.print( context );
      out.write("/views/join.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"account_info\">\r\n");
      out.write("\t\t\t\t\t");
 if(loginMember.getpImage() == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"프로필 사진\" src=\"");
      out.print( context );
      out.write("/resources/images/rocket.png\">\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"프로필 사진\" src=\"\">\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"membername\">");
      out.print( loginMember.getNickName() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"memberbtn\">\r\n");
      out.write("\t\t\t\t\t\t<button id='logoutBtn'>로그아웃</button>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"myPageBtn\">마이페이지</button>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"messageBtn\">쪽지함</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t<div id=\"content-area\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>nav</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/nav.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"nav\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>search</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/search.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"search-area\">\r\n");
      out.write("\t\t<form action=\"\" method=\"get\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"search\" id=\"search\" size=\"15\"> \r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"검색\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t\t<div id=\"menu-area\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"out-menu\">\r\n");
      out.write("\t\t\t\t\t\t<div>중고물품</div>\r\n");
      out.write("\t\t\t\t\t\t<li>중고 물품보기</li>\r\n");
      out.write("\t\t\t\t\t\t<li>중고 물품등록</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"out-menu\">\r\n");
      out.write("\t\t\t\t\t\t<div>공동구매</div>\r\n");
      out.write("\t\t\t\t\t\t<li>공동구매 목록조회</li>\r\n");
      out.write("\t\t\t\t\t\t<li>공동구매 캘린더</li>\r\n");
      out.write("\t\t\t\t\t\t<li>공동구매 물품등록</li>\r\n");
      out.write("\t\t\t\t\t\t<li>입금 확인 조회</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"out-menu\">\r\n");
      out.write("\t\t\t\t\t\t<div>자유게시판</div>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"out-menu\">\r\n");
      out.write("\t\t\t\t\t\t<div>관리자</div>\r\n");
      out.write("\t\t\t\t\t\t<li>회원 정보 관리</li>\r\n");
      out.write("\t\t\t\t\t\t<li>신고 목록 관리</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Top of this Month</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/tom.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"tom\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<b>이달의 로켓왕!</b>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<table id=\"tom-table\">\r\n");
      out.write("\t\t\t<tr id=\"table-head\">\r\n");
      out.write("\t\t\t\t<th>No.</th>\r\n");
      out.write("\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t<th>거래 수</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t<td>김로켓</td>\r\n");
      out.write("\t\t\t\t<td>16</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t\t<td>박마켓</td>\r\n");
      out.write("\t\t\t\t<td>14</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t\t<div id=\"join\">\r\n");
      out.write("\t\t\t\t\t<h1>회원 가입</h1>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<b><font size=\"8em\" color=\"orange\">R O C K E T</font></b>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<form id=\"joinForm\" method=\"post\" action=\"");
      out.print( context );
      out.write("/join.do\">\r\n");
      out.write("\t\t\t\t\t\t<div>아 이 디*</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"username_input\" name=\"userId\" id=\"userId\" size=\"32\" maxlength=\"20\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"id_check_button\" id=\"idCheckBtn\">중복확인</button>\r\n");
      out.write("\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div>비 밀 번 호*</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" size=\"32\" maxlength=\"20\" name=\"userPw\" id=\"userPw\" required><br> <br>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div>비 밀 번 호 재 확 인*</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" size=\"32\" maxlength=\"20\" name=\"pwCheck\" id=\"pwCheck\" required><br> <br>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div>비 밀 번 호 찾기 힌트*</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"pwHint\" id=\"pwHint\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"0\">질문을 선택해 주세요.</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>나의 보물 1호는?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>다시 태어나면 되고 싶은 것은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>유년 시절 가장 생각나는 친구의 이름은 ?</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>추억하고 싶은 날짜가 있다면?</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div>비 밀 번 호 찾기 답변*</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input size=\"32\" name=\"pwAns\" id=\"pwAns\" required><br> <br>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div>이 메 일*</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input size=\"32\" name=\"email\" id=\"email\" required><br> <br>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div>성 별*</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"gender\" value=\"M\" required checked>남자 \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"gender\" value=\"F\" required>여자\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div>닉 네 임*</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input size=\"16\" maxlength=\"15\" name=\"nickname\" id=\"nickname\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" id=\"checkNickname\">중복확인</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div>전화번호*</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"phone1\" id=\"phone1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>010</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>011</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>016</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t-\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" maxlength=\"4\" size=\"4\" name=\"phone2\" id=\"phone2\" required>\r\n");
      out.write("\t\t\t\t\t\t\t-\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" maxlength=\"4\" size=\"4\" name=\"phone3\" id=\"phone3\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div>계 좌 연 결</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"bank\" id=\"bank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">선택안함</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>카카오뱅크</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>국민은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>신한은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>하나은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>농협</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"banknum\" id=\"banknum\" size=\"25\" maxlength=\"25\" placeholder=\"계좌 번호 입력 칸\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div>간편결제 비밀번호</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"bankpw\" id=\"bankpw\" size=\"32\" maxlength=\"6\" placeholder=\"6자리 숫자를 입력해주세요.\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"checkterms\"><b> 약관 전체 동의</b>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"terms\"> 개인정보 수집 동의(필수) \r\n");
      out.write("\t\t\t\t\t\t\t<font color=\"gray\"><a>약관보기</a></font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"terms\" id=\"select\"> 마케팅 활용 및 광고성 정보 수신 동의(선택) \r\n");
      out.write("\t\t\t\t\t\t\t<font color=\"gray\"><a>약관보기</a></font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"mCheck\" id=\"mCheck\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t<br> <br>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" id=\"submit\" style=\"width: 380px\">가입 완료</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/footer.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer> 하단 </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>advertise</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/ad.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<aside id=\"advertise\">\r\n");
      out.write("\t\t<h3>광고 배너 입니다.</h3>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<a href=\"http://iei.or.kr\" target=\"_blank\">\r\n");
      out.write("\t\t\t<img id=\"adImg\" src=\"");
      out.print( context );
      out.write("/resources/images/kh.png\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<b>kh정보교육원</b>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<a href=\"http://nike.com\" target=\"_blank\">\r\n");
      out.write("\t\t\t<img id=\"adImg\" src=\"");
      out.print( context );
      out.write("/resources/images/ad1.jpg\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<b>에어 조던 1 로우</b>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<em>119,000</em>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<a href=\"http://nike.com\" target=\"_blank\">\r\n");
      out.write("\t\t\t<img id=\"adImg\" src=\"");
      out.print( context );
      out.write("/resources/images/ad1.jpg\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<b>에어 조던 1 로우</b>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<em>119,000</em>\r\n");
      out.write("\t</aside>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"");
      out.print( context );
      out.write("/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print( context );
      out.write("/resources/js/join.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
