/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-11-10 07:10:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import product.model.vo.*;
import java.util.*;
import board.model.vo.Board;
import group.model.vo.Group;
import board.model.vo.PageInfo;
import java.text.SimpleDateFormat;
import java.io.File;
import member.model.vo.Member;

public final class allSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/resources/globalVariable.jsp", Long.valueOf(1604828540617L));
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1604923087459L));
    _jspx_dependants.put("/WEB-INF/views/common/nav.jsp", Long.valueOf(1604923087467L));
    _jspx_dependants.put("/WEB-INF/views/common/tom.jsp", Long.valueOf(1604923087496L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("product.model.vo");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("group.model.vo.Group");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("board.model.vo.PageInfo");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("board.model.vo.Board");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   ArrayList<Product> pList = (ArrayList<Product>) request.getAttribute("pList");
   ArrayList<Board> bList = (ArrayList<Board>) request.getAttribute("bList");
   ArrayList<Group> gList = (ArrayList<Group>) request.getAttribute("gList");
   SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MM.dd");


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>로컬마켓</title>\r\n");
      out.write('\r');
      out.write('\n');

	String context = request.getContextPath();

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar context = \"");
      out.print( context );
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.print( context );
      out.write("/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<link rel = \"icon\" href = \"");
      out.print( context );
      out.write("/favicon.ico\">");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("   href=\"");
      out.print(context);
      out.write("/resources/css/base.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("   href=\"");
      out.print(context);
      out.write("/resources/css/content-area.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("   href=\"");
      out.print(context);
      out.write("/resources/css/content.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("   href=\"");
      out.print(context);
      out.write("/resources/css/mainpage.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("   href=\"");
      out.print(context);
      out.write("/resources/css/allSearch.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"wrap\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member)session.getAttribute("loginMember");
	String pImageName = null;
	if(loginMember != null && loginMember.getpImage() != null) {
		File f = new File(loginMember.getpImage());
		pImageName = f.getName();
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id='header'>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print( context );
      out.write("/\"> \r\n");
      out.write("\t\t\t\t<img id='logo-img' alt=\"로컬마켓\" src=\"");
      out.print( context );
      out.write("/resources/images/rocket.png\"></a>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print( context );
      out.write("/\"><span id=\"logo-text\">로켓</span></a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t <form action=\"allSearch.all\" method=\"get\" class=\"AllSearchForm\">\r\n");
      out.write("       \t \t<div id=\"header-search\">\r\n");
      out.write("            <input type=\"text\" name=\"word\" placeholder=\"검색어를 입력하세요!\"> \r\n");
      out.write("            <button class=\"glyphicon glyphicon-search\" id=\"AllSearchBtn\"></button>\r\n");
      out.write("         \t</div>\r\n");
      out.write("         </form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t");
 if(loginMember == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"account\">\r\n");
      out.write("\t\t\t\t\t<form action=\"");
      out.print( context );
      out.write("/login.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"id-area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"idInput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" id=\"login\" value=\"로그인\">로그인</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"pw-area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"pwInput\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" id=\"signup\" value=\"회원가입\" onclick=\"location.href='");
      out.print( context );
      out.write("/joinForm.do'\">회원가입</button><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" id=\"find\" value=\"ID/PW찾기\" onclick=\"findIDPW();\" style=\"float: right; width: 80px; font-weight:bold; border:none;\">\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"account_info\">\r\n");
      out.write("\t\t\t\t<div id=\"profileArea\">\r\n");
      out.write("\t\t\t\t");
 if(loginMember.getpImage() == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<label id=\"memberIcon\" class=\"glyphicon glyphicon-user\" style=\"top:15px; right: 30px;\"></label>\r\n");
      out.write("\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<img id=\"memberImg\" src=\"");
      out.print( context );
      out.write("/userProfile_uploadFiles/");
      out.print( pImageName );
      out.write("\">\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"membername\">");
      out.print( loginMember.getNickName() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"memberbtn\">\r\n");
      out.write("                  <button id='logoutBtn' onclick=\"location.href='");
      out.print( context );
      out.write("/logout.do'\">로그아웃</button>\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <button id=\"myPageBtn\" onclick=\"location.href='");
      out.print( context );
      out.write("/myPage.do'\">마이페이지</button>\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <button id=\"messageBtn\" onclick=\"location.href='");
      out.print( context );
      out.write("/message.do'\">쪽지함</button>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div id=\"alarm\">\r\n");
      out.write("                  <button class=\"glyphicon glyphicon-bell\" onclick=\"location.href='");
      out.print( context );
      out.write("/receiveP.do'\"></button>\r\n");
      out.write("               </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t");
 if(loginMember != null) { 
      out.write("\r\n");
      out.write("\t\t\tvar openProfile = function(closeCallback) {\r\n");
      out.write("\t\t\t    var win = window.open('setProfileImgForm.do', 'setProfileImgForm', 'width=500, height=450');\r\n");
      out.write("\t\t\t    var interval = window.setInterval(function() {\r\n");
      out.write("\t\t\t        try {\r\n");
      out.write("\t\t\t            if (win == null || win.closed) {\r\n");
      out.write("\t\t\t                window.clearInterval(interval);\r\n");
      out.write("\t\t\t                closeCallback(win);\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        catch (e) {\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    }, 1000);\r\n");
      out.write("\t\t\t    return win;\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"profileArea\").onclick = function() {\r\n");
      out.write("\t\t\t\topenProfile(function(win) {\r\n");
      out.write("\t\t\t\t\tlocation.reload(true);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t");
 } else { 
      out.write("\r\n");
      out.write("      \tfunction findIDPW() {\r\n");
      out.write("      \t\twindow.open('findIDPWForm.do', 'findIDPWForm', 'width=500, height=135');\r\n");
      out.write("\t\t}\r\n");
      out.write("      \r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("      <div id=\"content-area\">\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>nav</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/nav.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"nav\">\r\n");
      out.write("   \r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("            \r\n");
      out.write("            <!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("            <div id=\"menu-area\">\r\n");
      out.write("               <ul class=\"out-menu\">\r\n");
      out.write("                  <label class=\"glyphicon glyphicon-camera\"><div>중고물품</div></label>\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/list.pro'\">중고 물품보기</button></li>\r\n");
      out.write("                  ");
 if(loginMember != null) { 
      out.write("\r\n");
      out.write("                     <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/registerForm.pro'\">중고 물품등록</button></li>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("               <ul class=\"out-menu\">\r\n");
      out.write("                  <label class=\"glyphicon glyphicon-tag\"><div>공동구매</div></label>\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/groupList.do'\">공동구매 목록조회</button></li>\r\n");
      out.write("                  ");
 if(loginMember != null && loginMember.getRankCode() == 99) { 
      out.write("\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/groupWriteForm.do'\">공동구매 물품등록</button></li> \r\n");
      out.write("\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("               <ul class=\"out-menu menuBtn\" onclick=\"location.href='");
      out.print( context );
      out.write("/boardList.do'\">\r\n");
      out.write("                  <label class=\"glyphicon glyphicon-list\" class=\"menuBtn\"><div class=\"menuBtn\">자유게시판</div></label>\r\n");
      out.write("               </ul>\r\n");
      out.write("               ");
 if(loginMember != null && loginMember.getRankCode() == 99) { 
      out.write("\r\n");
      out.write("               <ul class=\"out-menu\">\r\n");
      out.write("                  <label class=\"glyphicon glyphicon-lock\"><div>관리자</div></label>\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/managerInfo.do'\">회원 정보 관리</li>\r\n");
      out.write("                  <li><button onclick=\"location.href='");
      out.print( context );
      out.write("/managerreport.do'\">신고 목록 관리</li>\r\n");
      out.write("               </ul>\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Top of this Month</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( context );
      out.write("/resources/css/tom.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"tom\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<b>이달의 로켓왕!</b>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table id=\"tom-table\">\r\n");
      out.write("\t\t\t<tr id=\"table-head\">\r\n");
      out.write("\t\t\t\t<th>No.</th>\r\n");
      out.write("\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t<th>거래 수</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<div id=\"loading\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print( context );
      out.write("/resources/images/loading.gif\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: 'topOfMonth.do',\r\n");
      out.write("\t\ttype: 'post',\r\n");
      out.write("\t\tdata: {first: 1, last: 3},\r\n");
      out.write("\t\tsuccess: function(data) {\t\r\n");
      out.write("\t\t\tvar table = document.getElementById(\"tom-table\");\r\n");
      out.write("\t\t\tfor(var i in data) {\r\n");
      out.write("\t\t\t\tvar tr = document.createElement(\"tr\");\r\n");
      out.write("\t\t\t\tvar td1 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\ttd1.innerHTML = data[i].rank;\r\n");
      out.write("\t\t\t\tvar td2 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\ttd2.innerHTML = data[i].nickname;\r\n");
      out.write("\t\t\t\tvar td3 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\ttd3.innerHTML = data[i].count;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttr.appendChild(td1);\r\n");
      out.write("\t\t\t\ttr.appendChild(td2);\r\n");
      out.write("\t\t\t\ttr.appendChild(td3);\r\n");
      out.write("\t\t\t\ttable.appendChild(tr);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('#tom-table').show();\r\n");
      out.write("\t\t\t$('#loading').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            <!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <script>\r\n");
      out.write("            $('.out-menu').click(function(){\r\n");
      out.write("               $(this).children().next().slideToggle();\r\n");
      out.write("            });\r\n");
      out.write("         </script>\r\n");
      out.write("         \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("      <!--  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ -->\r\n");
      out.write("      <h1>중고물품</h1>\r\n");
      out.write("      <br>\r\n");
      out.write("      <div class=\"product_list_wrap\">\r\n");
      out.write("         <table class=\"product_list\">\r\n");
      out.write("         <thead>\r\n");
      out.write("            ");
if (!pList.isEmpty()) {
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th width=\"50px\">번호</th>\r\n");
      out.write("               <th width=\"50px\">닉네임</th>\r\n");
      out.write("               <th width=\"200px\">제목</th>\r\n");
      out.write("               <th width=\"100px\">가격</th>\r\n");
      out.write("               <th width=\"50px\">조회수</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("         </thead>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <tbody>\r\n");
      out.write("         ");
if (pList.isEmpty()) {
      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("            <div class=\"noneProduct\">\r\n");
      out.write("               <label class=\"glyphicon glyphicon-alert\"> </label> <label>등록된\r\n");
      out.write("                  중고 물품이 없습니다.</label> <br>\r\n");
      out.write("               <br> <label id=\"golist\"\r\n");
      out.write("                  class=\"glyphicon glyphicon-hand-right\"></label>\r\n");
      out.write("               <button id=\"golist\"\r\n");
      out.write("                  onclick=\"location.href='");
      out.print(context);
      out.write("/list.pro'\">상품\r\n");
      out.write("                  목록으로 가기!</button>\r\n");
      out.write("               <br> <label id=\"goRegisterProduct\"\r\n");
      out.write("                  class=\"glyphicon glyphicon-hand-right\"></label>\r\n");
      out.write("               <button id=\"goRegisterProduct\"\r\n");
      out.write("                  onclick=\"location.href='");
      out.print(context);
      out.write("/registerForm.pro'\">상품\r\n");
      out.write("                  등록하러 가기!</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
} else {
      out.write("\r\n");
      out.write("            ");
for (int i = 0; i < pList.size(); i++) { 
      out.write("\r\n");
      out.write("            ");
 Product p = pList.get(i); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>");
      out.print(p.getProductId());
      out.write("</td>\r\n");
      out.write("               <td>");
      out.print(p.getNickname());
      out.write("</td>\r\n");
      out.write("               <td class=\"title\" onclick=\"pDetail(");
      out.print( p.getProductId() );
      out.write(");\">");
      out.print(p.getTitle());
      out.write("</td>\r\n");
      out.write("               <td>");
      out.print(p.getPrice());
      out.write("원</td>\r\n");
      out.write("               <td>");
      out.print(p.getProductCount());
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("         </tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("      \r\n");
      out.write("      <script>\r\n");
      out.write("            function pDetail(pNum) {\r\n");
      out.write("               ");
 if(loginMember != null) { 
      out.write("\r\n");
      out.write("               location.href='");
      out.print( context );
      out.write("/pdetail.pro?option=0&pId='+ pNum;\r\n");
      out.write("               ");
 } else { 
      out.write("\r\n");
      out.write("               alert('로그인 후 이용 가능합니다.');\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("         }\r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <br><br>\r\n");
      out.write("      \r\n");
      out.write("      <h4>최근 게시물 10개까지만 검색 되었습니다. 더 많은 게시물을 원하시면 밑 검색창을 이용하세요.</h4>\r\n");
      out.write("      \r\n");
      out.write("      <form action=\"productSearch.pro\" method=\"get\" class=\"productForm\">\r\n");
      out.write("         <br> <select name=\"searchOption\">\r\n");
      out.write("            <option value=\"TITLE\">제목</option>\r\n");
      out.write("            <option value=\"MEMBERNAME\">닉네임</option>\r\n");
      out.write("         </select> <input type=\"text\" name=\"word\" size=\"20\"\r\n");
      out.write("            placeholder=\"검색어를 입력해주세요\">\r\n");
      out.write("         <button id=\"searchProduct\" type=\"submit\">검색</button>\r\n");
      out.write("\r\n");
      out.write("      </form>\r\n");
      out.write("      \r\n");
      out.write("      <form action = \"");
      out.print( context );
      out.write("/deleteProduct.ad\" method=\"post\" id=\"deleteForm\"></form>\r\n");
      out.write("      \r\n");
      out.write("      <br><br><hr><br>\r\n");
      out.write("      \r\n");
      out.write("      <!--  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <h1>자유 게시판</h1>\r\n");
      out.write("      <br>\r\n");
      out.write("      <br>\r\n");
      out.write("      <div class=\"Board_list_wrap\">\r\n");
      out.write("         <table class=\"board_list\">\r\n");
      out.write("            <thead>\r\n");
      out.write("               ");
 if (!bList.isEmpty()) { 
      out.write("\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <th width=\"50px\">번호</th>\r\n");
      out.write("                  <th width=\"50px\">닉네임</th>\r\n");
      out.write("                  <th width=\"200px\">제목</th>\r\n");
      out.write("                  <th width=\"100px\">작성날</th>\r\n");
      out.write("                  <th width=\"50px\">조회수</th>\r\n");
      out.write("               </tr>\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("            </thead>\r\n");
      out.write("   \r\n");
      out.write("            <tbody>\r\n");
      out.write("               ");
 if (bList.isEmpty()) { 
      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("            <div class=\"noneBoard\">\r\n");
      out.write("               <label class=\"glyphicon glyphicon-alert\"> </label> <label>작성된 게시물이 없습니다.</label> \r\n");
      out.write("               <br><br> \r\n");
      out.write("               <label id=\"golist\" class=\"glyphicon glyphicon-hand-right\"></label>\r\n");
      out.write("               <button id=\"golist\" onclick=\"location.href='");
      out.print(context);
      out.write("/boardList.do'\">자유게시판 목록으로 가기!</button>\r\n");
      out.write("               <br> <label id=\"goRegisterProduct\" class=\"glyphicon glyphicon-hand-right\"></label>\r\n");
      out.write("               <button id=\"goRegisterProduct\" onclick=\"location.href='");
      out.print(context);
      out.write("/boardWriteForm.do'\">게시물 등록하러 가기!</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("               ");
} else {
      out.write("\r\n");
      out.write("               ");
 for (int i = 0; i < bList.size(); i++) { 
      out.write("\r\n");
      out.write("               ");
 Board b = bList.get(i); 
      out.write("\r\n");
      out.write("   \r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td>");
      out.print(b.getBoardNum());
      out.write("</td>\r\n");
      out.write("                  <td>");
      out.print(b.getNickName());
      out.write("</td>\r\n");
      out.write("                  <td class=\"title\" onclick=\"bDetail(");
      out.print( b.getBoardNum() );
      out.write(");\">");
      out.print(b.getBoardTitle());
      out.write("</td>\r\n");
      out.write("                  <td>");
      out.print(sdf.format(b.getCreateDate()));
      out.write("</td>\r\n");
      out.write("                  <td>");
      out.print(b.getBoardCount());
      out.write(" </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("         </table>\r\n");
      out.write("         \r\n");
      out.write("         <script>\r\n");
      out.write("            function bDetail(bNum) {\r\n");
      out.write("               location.href='");
      out.print( context );
      out.write("/boardDetail.do?bnum='+ bNum;\r\n");
      out.write("         }\r\n");
      out.write("         </script>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <br><br>\r\n");
      out.write("            <h4>최근 게시물 10개까지만 검색 되었습니다. 더 많은 게시물을 원하시면 밑 검색창을 이용하세요.</h4>\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("            <form action=\"boardSearch.do\" method=\"get\" class=\"boardForm\">\r\n");
      out.write("               <br>\r\n");
      out.write("               <select name=\"searchOption\">\r\n");
      out.write("                  <option value=\"TITLE\">제목</option>\r\n");
      out.write("                  <option value=\"BOARD_C\">내용</option>\r\n");
      out.write("                  <option value=\"MEMBERNAME\">작성자</option>\r\n");
      out.write("               </select>\r\n");
      out.write("               <input type=\"text\" name=\"word\" size=\"20\" placeholder=\"검색어를 입력해주세요\">\r\n");
      out.write("               <button id=\"search\" type=\"submit\">검색</button> \r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("             <br><br><hr><br>\r\n");
      out.write("      \r\n");
      out.write("      <!--  ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <h1>공동구매 게시판</h1>\r\n");
      out.write("      <br>\r\n");
      out.write("      <br>\r\n");
      out.write("      <div class=\"Group_list_wrap\">\r\n");
      out.write("         <table class=\"group_list\">\r\n");
      out.write("            <thead>\r\n");
      out.write("               ");
 if (!gList.isEmpty()) { 
      out.write("\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <th width=\"50px\">번호</th>\r\n");
      out.write("                  <th width=\"50px\">닉네임</th>\r\n");
      out.write("                  <th width=\"200px\">제목</th>\r\n");
      out.write("                  <th width=\"100px\">작성날</th>\r\n");
      out.write("                  <th width=\"50px\">조회수</th>\r\n");
      out.write("               </tr>\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("            </thead>\r\n");
      out.write("   \r\n");
      out.write("            <tbody>\r\n");
      out.write("               ");
 if (gList.isEmpty()) { 
      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("            <div class=\"noneGroup\">\r\n");
      out.write("               <label class=\"glyphicon glyphicon-alert\"> </label> <label>해당 공동구매 상품이 없습니다.</label> \r\n");
      out.write("               <br><br> \r\n");
      out.write("               <label id=\"golist\" class=\"glyphicon glyphicon-hand-right\"></label>\r\n");
      out.write("               <button id=\"golist\" onclick=\"location.href='");
      out.print(context);
      out.write("/groupList.do'\">공동구매 목록으로 가기!</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("               ");
} else {
      out.write("\r\n");
      out.write("               ");
 for (int i = 0; i < gList.size(); i++) { 
      out.write("\r\n");
      out.write("               ");
 Group g = gList.get(i); 
      out.write("\r\n");
      out.write("   \r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td>");
      out.print(g.getGroupNum());
      out.write("</td>\r\n");
      out.write("                  <td>");
      out.print(g.getNickName());
      out.write("</td>\r\n");
      out.write("                  <td class=\"title\" onclick=\"gDetail(");
      out.print( g.getGroupNum() );
      out.write(");\">");
      out.print(g.getGroupTitle());
      out.write("</td>\r\n");
      out.write("                  <td>");
      out.print(g.getgDate());
      out.write(" </td>\r\n");
      out.write("                  <td>");
      out.print(g.getGroupCount());
      out.write(" </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("         </table>\r\n");
      out.write("\r\n");
      out.write("      <script>\r\n");
      out.write("            function gDetail(bNum) {\r\n");
      out.write("               ");
 if(loginMember != null) { 
      out.write("\r\n");
      out.write("               location.href='");
      out.print( context );
      out.write("/groupDetail.do?bnum='+ bNum;\r\n");
      out.write("               ");
 } else { 
      out.write("\r\n");
      out.write("               alert('로그인 후 이용 가능합니다.');\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("         }\r\n");
      out.write("         </script>\r\n");
      out.write("            \r\n");
      out.write("            <br><br>\r\n");
      out.write("            <h4>최근 게시물 10개까지만 검색 되었습니다. 더 많은 게시물을 원하시면 밑 검색창을 이용하세요.</h4>\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("            <form action=\"groupSearch.do\" method=\"get\" class=\"groupForm\">\r\n");
      out.write("               <br>\r\n");
      out.write("               <select name=\"searchOption\">\r\n");
      out.write("                  <option value=\"TITLE\">제목</option>\r\n");
      out.write("                  <option value=\"BOARD_C\">내용</option>\r\n");
      out.write("                  <option value=\"MEMBERNAME\">작성자</option>\r\n");
      out.write("               </select>\r\n");
      out.write("               <input type=\"text\" name=\"word\" size=\"20\" placeholder=\"검색어를 입력해주세요\">\r\n");
      out.write("               <button id=\"search\" type=\"submit\">검색</button> \r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <br> <br>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("      <script src=\"");
      out.print(context);
      out.write("/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
